[general]
import = [
  '~/.config/alacritty/catppuccin-mocha.toml'
]
live_config_reload = true

[env]
TERM='xterm-256color'

[window]
padding.x = 10
padding.y = 10

option_as_alt = 'Both'

[font]
size = 14

[font.bold]
family = 'JetBrainsMono Nerd Font'
style = 'Bold'

[font.italic]
family = 'JetBrainsMono Nerd Font'

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'Regular'

[keyboard]
bindings = [
  { key = 'Left', mods = 'Alt', chars = "\u001BB" },
  { key = 'Right', mods = 'Alt', chars = "\u001BF" },
]

